#!/usr/bin/env bash
set -e

SECRETS_DIR_DEFAULT=${HOME}/secrets
SECRETS_DIR=${SECRETS_DIR:-${SECRETS_DIR_DEFAULT}}

docker run --rm -it \
 -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v ${SECRETS_DIR}/terraform.tfvars:/terraform/terraform.tfvars \
  qualimente/docker-infra-quickstart /bin/bash
